name: Rust CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  host-checks:
    name: Host Checks
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        check: [fmt, clippy, test]
        include:
          - check: fmt
            args: --all -- --check --color always
          - check: clippy
            args: --all-targets --all-features --workspace --target x86_64-unknown-linux-gnu -- -D warnings
          - check: test
            args: --target x86_64-unknown-linux-gnu
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Enable caching
        uses: Swatinem/rust-cache@v2
      - name: Run command
        run: cargo ${{ matrix.check }} ${{ matrix.args }}

  esp-checks:
    name: ESP32 Checks
    needs: host-checks
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        check: [build, clippy]
        include:
          - check: build
            args: --release --target xtensa-esp32s3-espidf
          - check: clippy
            args: --all-targets --all-features --workspace -- -D warnings
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Setup ESP Rust toolchain
        uses: esp-rs/xtensa-toolchain@v1.6
        with:
          default: true
          buildtargets: esp32s3
          ldproxy: true
      - name: Enable caching
        uses: Swatinem/rust-cache@v2
      - name: Run command
        run: cargo +esp ${{ matrix.check }} ${{ matrix.args }}
